import { ICard } from "./types.js";

// Keywords come from https://labyrinthos.co/blogs/tarot-card-meanings-list
export const deck: ICard[] = [
    {
        "name": "The Fool",
        "element": "Air",
        "sign": "",
        "quality": "",
        "planet": "Uranus",
        "uprightKeywords": "Beginnings, freedom, innocence, originality, adventure, idealism, spontaneity",
        "reversedKeywords": "Reckless, careless, distracted, naive, foolish, gullible, stale, dull",
        "uprightImageSlug": "ar00.jpg",
        "reversedImageSlug": "ar00_reversed.jpg",
        "id": "ar00",
        "color": 16777215,
        "uprightMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/the-fool-meaning-major-arcana-tarot-card-meanings#up",
        "reversedMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/the-fool-meaning-major-arcana-tarot-card-meanings#rev"
    },
    {
        "name": "The Magician",
        "element": "Air",
        "sign": "",
        "quality": "",
        "planet": "Mercury",
        "uprightKeywords": "Willpower, desire, being resourceful,, skill, ability, concentration, manifestation",
        "reversedKeywords": "Manipulation, cunning, trickery, wasted talent, illusion, deception",
        "uprightImageSlug": "ar01.jpg",
        "reversedImageSlug": "ar01_reversed.jpg",
        "id": "ar01",
        "color": 16777215,
        "uprightMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/the-magician-meaning-major-arcana-tarot-card-meanings#up",
        "reversedMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/the-magician-meaning-major-arcana-tarot-card-meanings#rev"
    },
    {
        "name": "The High Priestess",
        "element": "Water",
        "sign": "",
        "quality": "",
        "planet": "Moon",
        "uprightKeywords": "Unconscious, intuition, mystery, spirituality, higher power, inner voice",
        "reversedKeywords": "Repressed intuition, hidden motives, superficiality, confusion, cognitive dissonance",
        "uprightImageSlug": "ar02.jpg",
        "reversedImageSlug": "ar02_reversed.jpg",
        "id": "ar02",
        "color": 16777215,
        "uprightMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/the-high-priestess-meaning-major-arcana-tarot-card-meanings#up",
        "reversedMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/the-high-priestess-meaning-major-arcana-tarot-card-meanings#rev"
    },
    {
        "name": "The Empress",
        "element": "Earth",
        "sign": "",
        "quality": "",
        "planet": "Venus",
        "uprightKeywords": "Divine feminine, sensuality, fertility, nurturing, creativity, beauty, abundance, nature",
        "reversedKeywords": "Insecurity, overbearing, negligence, smothering, lack of growth, lack of progress",
        "uprightImageSlug": "ar03.jpg",
        "reversedImageSlug": "ar03_reversed.jpg",
        "id": "ar03",
        "color": 16777215,
        "uprightMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/the-empress-meaning-major-arcana-tarot-card-meanings#up",
        "reversedMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/the-empress-meaning-major-arcana-tarot-card-meanings#rev"
    },
    {
        "name": "The Emperor",
        "element": "Fire",
        "sign": "Aries",
        "quality": "",
        "planet": "",
        "uprightKeywords": "Stability, structure, protection, authority, control, practicality, focus, discipline",
        "reversedKeywords": "Tyrant, domineering, rigid, stubborn, lack of discipline, recklessness",
        "uprightImageSlug": "ar04.jpg",
        "reversedImageSlug": "ar04_reversed.jpg",
        "id": "ar04",
        "color": 16777215,
        "uprightMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/the-emperor-meaning-major-arcana-tarot-card-meanings#up",
        "reversedMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/the-emperor-meaning-major-arcana-tarot-card-meanings#rev"
    },
    {
        "name": "The Hierophant",
        "element": "Earth",
        "sign": "Taurus",
        "quality": "",
        "planet": "",
        "uprightKeywords": "Tradition, social groups, conventionality, conformity, education, knowledge, beliefs",
        "reversedKeywords": "Rebellion, unconventionality, non-conformity, new methods, ignorance",
        "uprightImageSlug": "ar05.jpg",
        "reversedImageSlug": "ar05_reversed.jpg",
        "id": "ar05",
        "color": 16777215,
        "uprightMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/the-hierophant-meaning-major-arcana-tarot-card-meanings#up",
        "reversedMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/the-hierophant-meaning-major-arcana-tarot-card-meanings#rev"
    },
    {
        "name": "The Lovers",
        "element": "Air",
        "sign": "Gemini",
        "quality": "",
        "planet": "",
        "uprightKeywords": "Love, unions, partnerships, relationships, choices, romance, balance, unity",
        "reversedKeywords": "Disharmony, imbalance, conflict, detachment, bad choices, indecision",
        "uprightImageSlug": "ar06.jpg",
        "reversedImageSlug": "ar06_reversed.jpg",
        "id": "ar06",
        "color": 16777215,
        "uprightMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/the-lovers-meaning-major-arcana-tarot-card-meanings#up",
        "reversedMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/the-lovers-meaning-major-arcana-tarot-card-meanings#rev"
    },
    {
        "name": "The Chariot",
        "element": "Water",
        "sign": "Cancer",
        "quality": "",
        "planet": "",
        "uprightKeywords": "Success, ambition, determination, willpower, control, self-discipline, focus",
        "reversedKeywords": "Forceful, no direction, no control, powerless, aggression, obstacles",
        "uprightImageSlug": "ar07.jpg",
        "reversedImageSlug": "ar07_reversed.jpg",
        "id": "ar07",
        "color": 16777215,
        "uprightMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/the-chariot-meaning-major-arcana-tarot-card-meanings#up",
        "reversedMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/the-chariot-meaning-major-arcana-tarot-card-meanings#rev"
    },
    {
        "name": "Strength",
        "element": "Fire",
        "sign": "Leo",
        "quality": "",
        "planet": "",
        "uprightKeywords": "Courage, bravery, confidence, compassion, self-confidence, inner power",
        "reversedKeywords": "Self-doubt, weakness, low confidence, inadequacy, cowardice, forcefulness",
        "uprightImageSlug": "ar08.jpg",
        "reversedImageSlug": "ar08_reversed.jpg",
        "id": "ar08",
        "color": 16777215,
        "uprightMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/strength-meaning-major-arcana-tarot-card-meanings#up",
        "reversedMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/strength-meaning-major-arcana-tarot-card-meanings#rev"
    },
    {
        "name": "The Hermit",
        "element": "Earth",
        "sign": "Virgo",
        "quality": "",
        "planet": "",
        "uprightKeywords": "Self-reflection, introspection, contemplation, withdrawal, solitude, search for self",
        "reversedKeywords": "Loneliness, isolation, recluse, being anti-social, rejection, returning to society",
        "uprightImageSlug": "ar09.jpg",
        "reversedImageSlug": "ar09_reversed.jpg",
        "id": "ar09",
        "color": 16777215,
        "uprightMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/the-hermit-meaning-major-arcana-tarot-card-meanings#up",
        "reversedMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/the-hermit-meaning-major-arcana-tarot-card-meanings#rev"
    },
    {
        "name": "Wheel of Fortune",
        "element": "Fire",
        "sign": "",
        "quality": "",
        "planet": "Jupiter",
        "uprightKeywords": "Change, cycles, fate, decisive moments, luck, fortune, unexpected events",
        "reversedKeywords": "Bad luck, lack of control, clinging to control, unwelcome changes, delays",
        "uprightImageSlug": "ar10.jpg",
        "reversedImageSlug": "ar10_reversed.jpg",
        "id": "ar10",
        "color": 16777215,
        "uprightMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/the-wheel-of-fortune-meaning-major-arcana-tarot-card-meanings#up",
        "reversedMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/the-wheel-of-fortune-meaning-major-arcana-tarot-card-meanings#rev"
    },
    {
        "name": "Justice",
        "element": "Air",
        "sign": "Libra",
        "quality": "",
        "planet": "",
        "uprightKeywords": "Justice, karma, consequence, accountability, law, truth, honesty, integrity, cause and effect",
        "reversedKeywords": "Injustice, retribution, dishonesty, corruption, dishonesty, unfairness, avoiding accountability",
        "uprightImageSlug": "ar11.jpg",
        "reversedImageSlug": "ar11_reversed.jpg",
        "id": "ar11",
        "color": 16777215,
        "uprightMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/justice-meaning-major-arcana-tarot-card-meanings#up",
        "reversedMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/justice-meaning-major-arcana-tarot-card-meanings#rev"
    },
    {
        "name": "The Hanged Man",
        "element": "Water",
        "sign": "",
        "quality": "",
        "planet": "Neptune",
        "uprightKeywords": "Sacrifice, waiting, uncertainty, lack of direction, perspective, contemplation",
        "reversedKeywords": "Stalling, disinterest, stagnation, avoiding sacrifice, standstill, apathy",
        "uprightImageSlug": "ar12.jpg",
        "reversedImageSlug": "ar12_reversed.jpg",
        "id": "ar12",
        "color": 16777215,
        "uprightMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/the-hanged-man-meaning-major-arcana-tarot-card-meanings#up",
        "reversedMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/the-hanged-man-meaning-major-arcana-tarot-card-meanings#rev"
    },
    {
        "name": "Death",
        "element": "Water",
        "sign": "Scorpio",
        "quality": "",
        "planet": "",
        "uprightKeywords": "Transformation, endings, change, transition, letting go, release",
        "reversedKeywords": "Fear of change, repeating negative patterns, resisting change, stagnancy, decay",
        "uprightImageSlug": "ar13.jpg",
        "reversedImageSlug": "ar13_reversed.jpg",
        "id": "ar13",
        "color": 16777215,
        "uprightMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/death-meaning-major-arcana-tarot-card-meanings#up",
        "reversedMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/death-meaning-major-arcana-tarot-card-meanings#rev"
    },
    {
        "name": "Temperance",
        "element": "Fire",
        "sign": "Sagittarius",
        "quality": "",
        "planet": "",
        "uprightKeywords": "Balance, peace, patience, moderation, calm, tranquillity, harmony, serenity",
        "reversedKeywords": "Imbalance, excess, extremes, discord, recklessness, hastiness",
        "uprightImageSlug": "ar14.jpg",
        "reversedImageSlug": "ar14_reversed.jpg",
        "id": "ar14",
        "color": 16777215,
        "uprightMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/temperance-meaning-major-arcana-tarot-card-meanings#up",
        "reversedMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/temperance-meaning-major-arcana-tarot-card-meanings#rev"
    },
    {
        "name": "The Devil",
        "element": "Earth",
        "sign": "Capricorn",
        "quality": "",
        "planet": "",
        "uprightKeywords": "Oppression, addiction, obsession, dependency, excess, powerlessness, limitations",
        "reversedKeywords": "Independence, freedom, revelation, release, reclaiming power, reclaiming control",
        "uprightImageSlug": "ar15.jpg",
        "reversedImageSlug": "ar15_reversed.jpg",
        "id": "ar15",
        "color": 16777215,
        "uprightMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/the-devil-meaning-major-arcana-tarot-card-meanings#up",
        "reversedMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/the-devil-meaning-major-arcana-tarot-card-meanings#rev"
    },
    {
        "name": "The Tower",
        "element": "Fire",
        "sign": "",
        "quality": "",
        "planet": "Mars",
        "uprightKeywords": "Disaster, destruction, upheaval, trauma, sudden change, chaos",
        "reversedKeywords": "Averting disaster, delaying the inevitable, resisting change",
        "uprightImageSlug": "ar16.jpg",
        "reversedImageSlug": "ar16_reversed.jpg",
        "id": "ar16",
        "color": 16777215,
        "uprightMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/the-tower-meaning-major-arcana-tarot-card-meanings#up",
        "reversedMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/the-tower-meaning-major-arcana-tarot-card-meanings#rev"
    },
    {
        "name": "The Star",
        "element": "Air",
        "sign": "Aquarius",
        "quality": "",
        "planet": "",
        "uprightKeywords": "Hope, inspiration, positivity, faith, renewal, healing, rejuvenation",
        "reversedKeywords": "Hopelessness, despair, negativity, lack of faith, despondent",
        "uprightImageSlug": "ar17.jpg",
        "reversedImageSlug": "ar17_reversed.jpg",
        "id": "ar17",
        "color": 16777215,
        "uprightMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/the-star-meaning-major-arcana-tarot-card-meanings#up",
        "reversedMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/the-star-meaning-major-arcana-tarot-card-meanings#rev"
    },
    {
        "name": "The Moon",
        "element": "Water",
        "sign": "Pisces",
        "quality": "",
        "planet": "",
        "uprightKeywords": "Illusion, intuition, uncertainty, confusion, complexity, secrets, unconscious",
        "reversedKeywords": "Fear, deception, anxiety, misunderstanding, misinterpretation, clarity, understanding",
        "uprightImageSlug": "ar18.jpg",
        "reversedImageSlug": "ar18_reversed.jpg",
        "id": "ar18",
        "color": 16777215,
        "uprightMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/the-moon-meaning-major-arcana-tarot-card-meanings#up",
        "reversedMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/the-moon-meaning-major-arcana-tarot-card-meanings#rev"
    },
    {
        "name": "The Sun",
        "element": "Fire",
        "sign": "",
        "quality": "",
        "planet": "Sun",
        "uprightKeywords": "Happiness, success, optimism, vitality, joy, confidence, happiness, truth",
        "reversedKeywords": "Blocked happiness, excessive enthusiasm, pessimism, unrealistic expectations, conceitedness",
        "uprightImageSlug": "ar19.jpg",
        "reversedImageSlug": "ar19_reversed.jpg",
        "id": "ar19",
        "color": 16777215,
        "uprightMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/the-sun-meaning-major-arcana-tarot-card-meanings#up",
        "reversedMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/the-sun-meaning-major-arcana-tarot-card-meanings#rev"
    },
    {
        "name": "Judgement",
        "element": "Fire/Water",
        "sign": "",
        "quality": "",
        "planet": "Pluto",
        "uprightKeywords": "Self-evaluation, awakening, renewal, purpose, reflection, reckoning",
        "reversedKeywords": "Self-doubt, lack of self-awareness, failure to learn lessons, self-loathing",
        "uprightImageSlug": "ar20.jpg",
        "reversedImageSlug": "ar20_reversed.jpg",
        "id": "ar20",
        "color": 16777215,
        "uprightMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/judgement-meaning-major-arcana-tarot-card-meanings#up",
        "reversedMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/judgement-meaning-major-arcana-tarot-card-meanings#rev"
    },
    {
        "name": "The World",
        "element": "Earth",
        "sign": "",
        "quality": "",
        "planet": "Saturn",
        "uprightKeywords": "Completion, achievement, fulfilment, sense of belonging, wholeness, harmony",
        "reversedKeywords": "Lack of closure, lack of achievement, feeling incomplete, emptiness",
        "uprightImageSlug": "ar21.jpg",
        "reversedImageSlug": "ar21_reversed.jpg",
        "id": "ar21",
        "color": 16777215,
        "uprightMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/the-world-meaning-major-arcana-tarot-card-meanings#up",
        "reversedMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/the-world-meaning-major-arcana-tarot-card-meanings#rev"
    },
    {
        "name": "Ace of Wands",
        "element": "Fire",
        "sign": "Aries/Leo/Sagittarius",
        "quality": "",
        "planet": "",
        "uprightKeywords": "Inspiration, creative spark, new initiative, new passion, enthusiasm, energy",
        "reversedKeywords": "Delays, blocks, lack of passion, lack of energy, hesitancy, creative blocks",
        "uprightImageSlug": "waac.jpg",
        "reversedImageSlug": "waac_reversed.jpg",
        "id": "waac",
        "color": 14596231,
        "uprightMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/ace-of-wands-meaning-tarot-card-meanings#up",
        "reversedMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/ace-of-wands-meaning-tarot-card-meanings#rev"
    },
    {
        "name": "Two of Wands",
        "element": "Fire",
        "sign": "Aries",
        "quality": "Cardinal",
        "planet": "Mars",
        "uprightKeywords": "Planning, first steps, making decisions, leaving comfort, taking risks",
        "reversedKeywords": "Bad planning, overanalyzing, not taking action, playing it safe, avoiding risk",
        "uprightImageSlug": "wa02.jpg",
        "reversedImageSlug": "wa02_reversed.jpg",
        "id": "wa02",
        "color": 14596231,
        "uprightMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/two-of-wands-meaning-tarot-card-meanings#up",
        "reversedMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/two-of-wands-meaning-tarot-card-meanings#rev"
    },
    {
        "name": "Three of Wands",
        "element": "Fire",
        "sign": "Aries",
        "quality": "Cardinal",
        "planet": "Sun",
        "uprightKeywords": "Momentum, confidence, expansion, growth, foresight, looking ahead",
        "reversedKeywords": "Restriction, limitations, lack of progress, obstacles, delays, frustration",
        "uprightImageSlug": "wa03.jpg",
        "reversedImageSlug": "wa03_reversed.jpg",
        "id": "wa03",
        "color": 14596231,
        "uprightMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/three-of-wands-meaning-tarot-card-meanings#up",
        "reversedMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/three-of-wands-meaning-tarot-card-meanings#rev"
    },
    {
        "name": "Four of Wands",
        "element": "Fire",
        "sign": "Aries",
        "quality": "Cardinal",
        "planet": "Venus",
        "uprightKeywords": "Community, home, celebrations, reunions, parties, gatherings, stability, belonging",
        "reversedKeywords": "Lack of support, instability, feeling unwelcome, transience, lack of roots, home conflict",
        "uprightImageSlug": "wa04.jpg",
        "reversedImageSlug": "wa04_reversed.jpg",
        "id": "wa04",
        "color": 14596231,
        "uprightMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/four-of-wands-meaning-tarot-card-meanings#up",
        "reversedMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/four-of-wands-meaning-tarot-card-meanings#rev"
    },
    {
        "name": "Five of Wands",
        "element": "Fire",
        "sign": "Leo",
        "quality": "Fixed",
        "planet": "Saturn",
        "uprightKeywords": "Conflict, competition, arguments, aggression, tension, rivals, clashes of ego",
        "reversedKeywords": "End of conflict, cooperation, agreements, truces, harmony, peace, avoiding conflict",
        "uprightImageSlug": "wa05.jpg",
        "reversedImageSlug": "wa05_reversed.jpg",
        "id": "wa05",
        "color": 14596231,
        "uprightMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/five-of-wands-meaning-tarot-card-meanings#up",
        "reversedMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/five-of-wands-meaning-tarot-card-meanings#rev"
    },
    {
        "name": "Six of Wands",
        "element": "Fire",
        "sign": "Leo",
        "quality": "Fixed",
        "planet": "Jupiter",
        "uprightKeywords": "Success, victory, triumph, rewards, recognition, praise, acclaim, pride",
        "reversedKeywords": "Failure, lack of recognition, no rewards, lack of achievement",
        "uprightImageSlug": "wa06.jpg",
        "reversedImageSlug": "wa06_reversed.jpg",
        "id": "wa06",
        "color": 14596231,
        "uprightMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/six-of-wands-meaning-tarot-card-meanings#up",
        "reversedMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/six-of-wands-meaning-tarot-card-meanings#rev"
    },
    {
        "name": "Seven of Wands",
        "element": "Fire",
        "sign": "Leo",
        "quality": "Fixed",
        "planet": "Mars",
        "uprightKeywords": "Protectiveness, standing up for yourself, defending yourself, protecting territory",
        "reversedKeywords": "Giving up, admitting defeat, yielding, lack of self belief, surrender",
        "uprightImageSlug": "wa07.jpg",
        "reversedImageSlug": "wa07_reversed.jpg",
        "id": "wa07",
        "color": 14596231,
        "uprightMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/seven-of-wands-meaning-tarot-card-meanings#up",
        "reversedMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/seven-of-wands-meaning-tarot-card-meanings#rev"
    },
    {
        "name": "Eight of Wands",
        "element": "Fire",
        "sign": "Sagittarius",
        "quality": "Mutable",
        "planet": "Mercury",
        "uprightKeywords": "Movement, speed, progress, quick decisions, sudden changes, excitement",
        "reversedKeywords": "Waiting, slowness, chaos, delays, losing momentum, hastiness, being unprepared",
        "uprightImageSlug": "wa08.jpg",
        "reversedImageSlug": "wa08_reversed.jpg",
        "id": "wa08",
        "color": 14596231,
        "uprightMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/eight-of-wands-meaning-tarot-card-meanings#up",
        "reversedMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/eight-of-wands-meaning-tarot-card-meanings#rev"
    },
    {
        "name": "Nine of Wands",
        "element": "Fire",
        "sign": "Sagittarius",
        "quality": "Mutable",
        "planet": "Moon",
        "uprightKeywords": "Last stand, persistence, grit, resilience, perseverance, close to success, fatigue",
        "reversedKeywords": "Stubbornness, rigidity, defensiveness, refusing compromise, giving up",
        "uprightImageSlug": "wa09.jpg",
        "reversedImageSlug": "wa09_reversed.jpg",
        "id": "wa09",
        "color": 14596231,
        "uprightMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/nine-of-wands-meaning-tarot-card-meanings#up",
        "reversedMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/nine-of-wands-meaning-tarot-card-meanings#rev"
    },
    {
        "name": "Ten of Wands",
        "element": "Fire",
        "sign": "Sagittarius",
        "quality": "Mutable",
        "planet": "Saturn",
        "uprightKeywords": "Burden, responsibility, duty, stress, obligation, burning out, struggles",
        "reversedKeywords": "Failure to delegate, shouldering too much responsibility, collapse, breakdown",
        "uprightImageSlug": "wa10.jpg",
        "reversedImageSlug": "wa10_reversed.jpg",
        "id": "wa10",
        "color": 14596231,
        "uprightMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/ten-of-wands-meaning-tarot-card-meanings#up",
        "reversedMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/ten-of-wands-meaning-tarot-card-meanings#rev"
    },
    {
        "name": "Page of Wands",
        "element": "Fire",
        "sign": "",
        "quality": "",
        "planet": "",
        "uprightKeywords": "adventure, excitement, fresh ideas, cheerfulness, energetic, fearless, extroverted",
        "reversedKeywords": "hasty, impatient, lacking ideas, tantrums, laziness, boring, unreliable, distracted",
        "uprightImageSlug": "wapa.jpg",
        "reversedImageSlug": "wapa_reversed.jpg",
        "id": "wapa",
        "color": 14596231,
        "uprightMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/page-of-wands-meaning-tarot-card-meanings#up",
        "reversedMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/page-of-wands-meaning-tarot-card-meanings#rev"
    },
    {
        "name": "Knight of Wands",
        "element": "Water/Fire",
        "sign": "Scorpio/Sagittarius",
        "quality": "",
        "planet": "",
        "uprightKeywords": "Courageous, energetic, charming, hero, rebellious, hot tempered, free spirit",
        "reversedKeywords": "Arrogant, reckless, impatient, lack of self control, passive, volatile, domineering",
        "uprightImageSlug": "wakn.jpg",
        "reversedImageSlug": "wakn_reversed.jpg",
        "id": "wakn",
        "color": 14596231,
        "uprightMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/knight-of-wands-meaning-tarot-card-meanings#up",
        "reversedMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/knight-of-wands-meaning-tarot-card-meanings#rev"
    },
    {
        "name": "Queen of Wands",
        "element": "Water/Fire",
        "sign": "Pisces/Aries",
        "quality": "",
        "planet": "",
        "uprightKeywords": "Confident, self-assured, passionate, determined, social, charismatic, vivacious, optimistic",
        "reversedKeywords": "Demanding, vengeful, low confidence, jealous, selfish, temperamental, bully",
        "uprightImageSlug": "waqu.jpg",
        "reversedImageSlug": "waqu_reversed.jpg",
        "id": "waqu",
        "color": 14596231,
        "uprightMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/queen-of-wands-meaning-tarot-card-meanings#up",
        "reversedMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/queen-of-wands-meaning-tarot-card-meanings#rev"
    },
    {
        "name": "King of Wands (Knight of Wands)",
        "element": "Water/Fire",
        "sign": "Cancer/Leo",
        "quality": "",
        "planet": "",
        "uprightKeywords": "Leadership, vision, big picture, taking control, daring decisions, boldness, optimism",
        "reversedKeywords": "Forceful, domineering, tyrant, vicious, powerless, ineffective, weak leader",
        "uprightImageSlug": "waki.jpg",
        "reversedImageSlug": "waki_reversed.jpg",
        "id": "waki",
        "color": 14596231,
        "uprightMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/king-of-wands-meaning-tarot-card-meanings#up",
        "reversedMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/king-of-wands-meaning-tarot-card-meanings#rev"
    },
    {
        "name": "Ace of Pentacles",
        "element": "Earth",
        "sign": "Taurus/Virgo/Capricorn",
        "quality": "",
        "planet": "",
        "uprightKeywords": "New opportunities, resources, abundance, prosperity, security, stability, manifestation",
        "reversedKeywords": "Missed chances, scarcity, deficiency, instability, stinginess, bad investments",
        "uprightImageSlug": "peac.jpg",
        "reversedImageSlug": "peac_reversed.jpg",
        "id": "peac",
        "color": 16776960,
        "uprightMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/ace-of-pentacles-meaning-tarot-card-meanings#up",
        "reversedMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/ace-of-pentacles-meaning-tarot-card-meanings#rev"
    },
    {
        "name": "Two of Pentacles",
        "element": "Earth",
        "sign": "Capricorn",
        "quality": "Cardinal",
        "planet": "Jupiter",
        "uprightKeywords": "Balancing resources, adaptation, resourcefulness, flexibility, stretching resources",
        "reversedKeywords": "Imbalance, unorganized, overwhelmed, messiness, chaos, overextending",
        "uprightImageSlug": "pe02.jpg",
        "reversedImageSlug": "pe02_reversed.jpg",
        "id": "pe02",
        "color": 16776960,
        "uprightMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/two-of-pentacles-meaning-tarot-card-meanings#up",
        "reversedMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/two-of-pentacles-meaning-tarot-card-meanings#rev"
    },
    {
        "name": "Three of Pentacles",
        "element": "Earth",
        "sign": "Capricorn",
        "quality": "Cardinal",
        "planet": "Mars",
        "uprightKeywords": "Teamwork, shared goals, collaboration, apprenticeship, effort, pooling energy",
        "reversedKeywords": "Lack of cohesion, lack of teamwork, apathy, poor motivation, conflict, ego, competition",
        "uprightImageSlug": "pe03.jpg",
        "reversedImageSlug": "pe03_reversed.jpg",
        "id": "pe03",
        "color": 16776960,
        "uprightMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/three-of-pentacles-meaning-tarot-card-meanings#up",
        "reversedMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/three-of-pentacles-meaning-tarot-card-meanings#rev"
    },
    {
        "name": "Four of Pentacles",
        "element": "Earth",
        "sign": "Capricorn",
        "quality": "Cardinal",
        "planet": "Sun",
        "uprightKeywords": "Possessiveness, insecurity, hoarding, stinginess, stability, security, savings, materialism, wealth, frugality, boundaries, guardedness",
        "reversedKeywords": "Generosity, giving, spending, openness, financial insecurity, reckless spending",
        "uprightImageSlug": "pe04.jpg",
        "reversedImageSlug": "pe04_reversed.jpg",
        "id": "pe04",
        "color": 16776960,
        "uprightMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/four-of-pentacles-meaning-tarot-card-meanings#up",
        "reversedMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/four-of-pentacles-meaning-tarot-card-meanings#rev"
    },
    {
        "name": "Five of Pentacles",
        "element": "Earth",
        "sign": "Taurus",
        "quality": "Fixed",
        "planet": "Mercury",
        "uprightKeywords": "Hardship, loss, isolation, feeling abandoned, adversity, struggle, unemployment, alienation, disgrace",
        "reversedKeywords": "Positive changes, recovery from loss, overcoming adversity, forgiveness, feeling welcomed",
        "uprightImageSlug": "pe05.jpg",
        "reversedImageSlug": "pe05_reversed.jpg",
        "id": "pe05",
        "color": 16776960,
        "uprightMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/five-of-pentacles-meaning-tarot-card-meanings#up",
        "reversedMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/five-of-pentacles-meaning-tarot-card-meanings#rev"
    },
    {
        "name": "Six of Pentacles",
        "element": "Earth",
        "sign": "Taurus",
        "quality": "Fixed",
        "planet": "Moon",
        "uprightKeywords": "Generosity, charity, community, material help, support, sharing, giving and receiving, gratitude",
        "reversedKeywords": "Power dynamics, abuse of generosity, strings attached gifts, inequality, extortion",
        "uprightImageSlug": "pe06.jpg",
        "reversedImageSlug": "pe06_reversed.jpg",
        "id": "pe06",
        "color": 16776960,
        "uprightMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/six-of-pentacles-meaning-tarot-card-meanings#up",
        "reversedMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/six-of-pentacles-meaning-tarot-card-meanings#rev"
    },
    {
        "name": "Seven of Pentacles",
        "element": "Earth",
        "sign": "Taurus",
        "quality": "Fixed",
        "planet": "Saturn",
        "uprightKeywords": "Harvest, rewards, results, growth, progress, perseverance, patience, planning",
        "reversedKeywords": "Unfinished work, procrastination, low effort, waste, lack of growth, setbacks, impatience, lack of reward",
        "uprightImageSlug": "pe07.jpg",
        "reversedImageSlug": "pe07_reversed.jpg",
        "id": "pe07",
        "color": 16776960,
        "uprightMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/seven-of-pentacles-meaning-tarot-card-meanings#up",
        "reversedMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/seven-of-pentacles-meaning-tarot-card-meanings#rev"
    },
    {
        "name": "Eight of Pentacles",
        "element": "Earth",
        "sign": "Virgo",
        "quality": "Mutable",
        "planet": "Sun",
        "uprightKeywords": "Skill, talent, craftsmanship, quality, high standards, expertise, mastery, commitment, dedication, accomplishment",
        "reversedKeywords": "Lack of quality, rushed job, bad reputation, lack of motivation, mediocrity, laziness, low skill, dead-end job",
        "uprightImageSlug": "pe08.jpg",
        "reversedImageSlug": "pe08_reversed.jpg",
        "id": "pe08",
        "color": 16776960,
        "uprightMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/eight-of-pentacles-meaning-tarot-card-meanings#up",
        "reversedMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/eight-of-pentacles-meaning-tarot-card-meanings#rev"
    },
    {
        "name": "Nine of Pentacles",
        "element": "Earth",
        "sign": "Virgo",
        "quality": "Mutable",
        "planet": "Venus",
        "uprightKeywords": "Rewarded efforts, success, achievement, independence, leisure, material security, self-sufficiency",
        "reversedKeywords": "Being guarded, living beyond means, material instability, reckless spending, superficiality",
        "uprightImageSlug": "pe09.jpg",
        "reversedImageSlug": "pe09_reversed.jpg",
        "id": "pe09",
        "color": 16776960,
        "uprightMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/nine-of-pentacles-meaning-tarot-card-meanings#up",
        "reversedMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/nine-of-pentacles-meaning-tarot-card-meanings#rev"
    },
    {
        "name": "Ten of Pentacles",
        "element": "Earth",
        "sign": "Virgo",
        "quality": "Mutable",
        "planet": "Mercury",
        "uprightKeywords": "Legacy, roots, family, ancestry, inheritance, windfall, foundations, privilege, affluence, stability, tradition",
        "reversedKeywords": "Family disputes, bankruptcy, debt, fleeting success, conflict over money, instability, breaking traditions",
        "uprightImageSlug": "pe10.jpg",
        "reversedImageSlug": "pe10_reversed.jpg",
        "id": "pe10",
        "color": 16776960,
        "uprightMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/ten-of-pentacles-meaning-tarot-card-meanings#up",
        "reversedMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/ten-of-pentacles-meaning-tarot-card-meanings#rev"
    },
    {
        "name": "Page of Pentacles",
        "element": "Earth",
        "sign": "",
        "quality": "",
        "planet": "",
        "uprightKeywords": "Ambitious, diligent, goal oriented, planner, consistent, star student, studious, grounded, loyal, faithful, dependable",
        "reversedKeywords": "Foolish, immature, irresponsible, lazy, underachiever, procrastinator, missed chances, poor prospects",
        "uprightImageSlug": "pepa.jpg",
        "reversedImageSlug": "pepa_reversed.jpg",
        "id": "pepa",
        "color": 16776960,
        "uprightMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/page-of-pentacles-meaning-tarot-card-meanings#up",
        "reversedMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/page-of-pentacles-meaning-tarot-card-meanings#rev"
    },
    {
        "name": "Knight of Pentacles (Prince of Disks)",
        "element": "Fire/Earth",
        "sign": "Leo/Virgo",
        "quality": "",
        "planet": "",
        "uprightKeywords": "Practical, reliable, efficient, stoic, slow and steady, hard-working, committed, patient, conservative",
        "reversedKeywords": "Workaholic, laziness, dull, boring, no initiative, cheap, irresponsible, gambler, risky investments",
        "uprightImageSlug": "pekn.jpg",
        "reversedImageSlug": "pekn_reversed.jpg",
        "id": "pekn",
        "color": 16776960,
        "uprightMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/knight-of-pentacles-meaning-tarot-card-meanings#up",
        "reversedMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/knight-of-pentacles-meaning-tarot-card-meanings#rev"
    },
    {
        "name": "Queen of Pentacles",
        "element": "Fire/Earth",
        "sign": "Sagittarius/Capricorn",
        "quality": "",
        "planet": "",
        "uprightKeywords": "Generous, caring, nurturing, homebody, good business sense, practical, comforting, welcoming, sensible, luxurious",
        "reversedKeywords": "Selfish, unkempt, jealous, insecure, greedy, materialistic, gold digger, intolerant, self-absorbed, envious",
        "uprightImageSlug": "pequ.jpg",
        "reversedImageSlug": "pequ_reversed.jpg",
        "id": "pequ",
        "color": 16776960,
        "uprightMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/queen-of-pentacles-meaning-tarot-card-meanings#up",
        "reversedMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/queen-of-pentacles-meaning-tarot-card-meanings#rev"
    },
    {
        "name": "King of Pentacles",
        "element": "Fire/Earth",
        "sign": "Aries/Taurus",
        "quality": "",
        "planet": "",
        "uprightKeywords": "Abundance, prosperity, security, ambitious, safe, kind, patriarchal, protective, businessman, provider, sensual, reliable",
        "reversedKeywords": "Greed, materialistic, wasteful, chauvanist, poor financial decisions, gambler, exploitative, possessive",
        "uprightImageSlug": "peki.jpg",
        "reversedImageSlug": "peki_reversed.jpg",
        "id": "peki",
        "color": 16776960,
        "uprightMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/king-of-pentacles-meaning-tarot-card-meanings#up",
        "reversedMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/king-of-pentacles-meaning-tarot-card-meanings#rev"
    },
    {
        "name": "Ace of Cups",
        "element": "Water",
        "sign": "Cancer/Scorpio/Pisces",
        "quality": "",
        "planet": "",
        "uprightKeywords": "Love, new feelings, emotional awakening, creativity, spirituality, intuition",
        "reversedKeywords": "Coldness, emptiness, emotional loss, blocked creativity, feeling unloved, gloominess",
        "uprightImageSlug": "cuac.jpg",
        "reversedImageSlug": "cuac_reversed.jpg",
        "id": "cuac",
        "color": 49151,
        "uprightMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/ace-of-cups-meaning-tarot-card-meanings#up",
        "reversedMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/ace-of-cups-meaning-tarot-card-meanings#rev"
    },
    {
        "name": "Two of Cups",
        "element": "Water",
        "sign": "Cancer",
        "quality": "Cardinal",
        "planet": "Venus",
        "uprightKeywords": "Unity, partnership, attraction, connection, close bonds, joining forces, mutual respect",
        "reversedKeywords": "Separation, rejection, division, imbalance, tension, bad communication, withdrawal",
        "uprightImageSlug": "cu02.jpg",
        "reversedImageSlug": "cu02_reversed.jpg",
        "id": "cu02",
        "color": 49151,
        "uprightMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/two-of-cups-meaning-tarot-card-meanings#up",
        "reversedMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/two-of-cups-meaning-tarot-card-meanings#rev"
    },
    {
        "name": "Three of Cups",
        "element": "Water",
        "sign": "Cancer",
        "quality": "Cardinal",
        "planet": "Mercury",
        "uprightKeywords": "Friendship, community, gatherings, celebrations, group events, social events",
        "reversedKeywords": "Gossip, scandal, excess, isolation, loneliness, solitude, imbalanced social life",
        "uprightImageSlug": "cu03.jpg",
        "reversedImageSlug": "cu03_reversed.jpg",
        "id": "cu03",
        "color": 49151,
        "uprightMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/three-of-cups-meaning-tarot-card-meanings#up",
        "reversedMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/three-of-cups-meaning-tarot-card-meanings#rev"
    },
    {
        "name": "Four of Cups",
        "element": "Water",
        "sign": "Cancer",
        "quality": "Cardinal",
        "planet": "Moon",
        "uprightKeywords": "Apathy, contemplation, feeling disconnected, melancholy, boredom, indifference, discontent",
        "reversedKeywords": "Clarity, awareness, acceptance, choosing happiness, depression, negativity",
        "uprightImageSlug": "cu04.jpg",
        "reversedImageSlug": "cu04_reversed.jpg",
        "id": "cu04",
        "color": 49151,
        "uprightMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/four-of-cups-meaning-tarot-card-meanings#up",
        "reversedMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/four-of-cups-meaning-tarot-card-meanings#rev"
    },
    {
        "name": "Five of Cups",
        "element": "Water",
        "sign": "Scorpio",
        "quality": "Fixed",
        "planet": "Mars",
        "uprightKeywords": "Loss, grief, disappointment, sadness, mourning, discontent, feeling let down",
        "reversedKeywords": "Acceptance, moving on, finding peace, contentment, seeing positives",
        "uprightImageSlug": "cu05.jpg",
        "reversedImageSlug": "cu05_reversed.jpg",
        "id": "cu05",
        "color": 49151,
        "uprightMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/five-of-cups-meaning-tarot-card-meanings#up",
        "reversedMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/five-of-cups-meaning-tarot-card-meanings#rev"
    },
    {
        "name": "Six of Cups",
        "element": "Water",
        "sign": "Scorpio",
        "quality": "Fixed",
        "planet": "Sun",
        "uprightKeywords": "Nostalgia, memories, familiarity, healing, comfort, sentimentality, pleasure",
        "reversedKeywords": "Stuck in past, moving forward, leaving home, independence",
        "uprightImageSlug": "cu06.jpg",
        "reversedImageSlug": "cu06_reversed.jpg",
        "id": "cu06",
        "color": 49151,
        "uprightMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/six-of-cups-meaning-tarot-card-meanings#up",
        "reversedMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/six-of-cups-meaning-tarot-card-meanings#rev"
    },
    {
        "name": "Seven of Cups",
        "element": "Water",
        "sign": "Scorpio",
        "quality": "Fixed",
        "planet": "Venus",
        "uprightKeywords": "Choices, searching for purpose, illusion, fantasy, daydreaming, wishful thinking, indecision",
        "reversedKeywords": "Lack of purpose, disarray, confusion, diversion, distractions, clarity, making choices",
        "uprightImageSlug": "cu07.jpg",
        "reversedImageSlug": "cu07_reversed.jpg",
        "id": "cu07",
        "color": 49151,
        "uprightMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/seven-of-cups-meaning-tarot-card-meanings#up",
        "reversedMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/seven-of-cups-meaning-tarot-card-meanings#rev"
    },
    {
        "name": "Eight of Cups",
        "element": "Water",
        "sign": "Pisces",
        "quality": "Mutable",
        "planet": "Saturn",
        "uprightKeywords": "Abandonment, walking away, letting go, searching for truth, leaving behind",
        "reversedKeywords": "Stagnation, monotony, accepting less, avoidance, fear of change, staying in bad situation",
        "uprightImageSlug": "cu08.jpg",
        "reversedImageSlug": "cu08_reversed.jpg",
        "id": "cu08",
        "color": 49151,
        "uprightMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/eight-of-cups-meaning-tarot-card-meanings#up",
        "reversedMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/eight-of-cups-meaning-tarot-card-meanings#rev"
    },
    {
        "name": "Nine of Cups",
        "element": "Water",
        "sign": "Pisces",
        "quality": "Mutable",
        "planet": "Jupiter",
        "uprightKeywords": "Wishes coming true, contentment, satisfaction, success, achievements, recognition, pleasure",
        "reversedKeywords": "Unhappiness, lack of fulfilment, disappointment, underachievement, arrogance, snobbery",
        "uprightImageSlug": "cu09.jpg",
        "reversedImageSlug": "cu09_reversed.jpg",
        "id": "cu09",
        "color": 49151,
        "uprightMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/nine-of-cups-meaning-tarot-card-meanings#up",
        "reversedMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/nine-of-cups-meaning-tarot-card-meanings#rev"
    },
    {
        "name": "Ten of Cups",
        "element": "Water",
        "sign": "Pisces",
        "quality": "Mutable",
        "planet": "Mars",
        "uprightKeywords": "Happiness, homecomings, fulfillment, emotional stability, security, domestic harmony",
        "reversedKeywords": "Unhappy home, separation, domestic conflict, disharmony, isolation​",
        "uprightImageSlug": "cu10.jpg",
        "reversedImageSlug": "cu10_reversed.jpg",
        "id": "cu10",
        "color": 49151,
        "uprightMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/ten-of-cups-meaning-tarot-card-meanings#up",
        "reversedMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/ten-of-cups-meaning-tarot-card-meanings#rev"
    },
    {
        "name": "Page of Cups",
        "element": "Water",
        "sign": "",
        "quality": "",
        "planet": "",
        "uprightKeywords": "Idealism, sensitivity, dreamer, naivete, innocence, inner child, head in the clouds",
        "reversedKeywords": "Emotional vulnerability, immaturity, neglecting inner child, escapism, insecurity",
        "uprightImageSlug": "cupa.jpg",
        "reversedImageSlug": "cupa_reversed.jpg",
        "id": "cupa",
        "color": 49151,
        "uprightMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/page-of-cups-meaning-tarot-card-meanings#up",
        "reversedMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/page-of-cups-meaning-tarot-card-meanings#rev"
    },
    {
        "name": "Knight of Cups",
        "element": "Air/Water",
        "sign": "Aquarius/Pisces",
        "quality": "",
        "planet": "",
        "uprightKeywords": "Idealist, charming, artistic, graceful, tactful, diplomatic, mediator, negotiator",
        "reversedKeywords": "Disappointment, tantrums, moodiness, turmoil, avoiding conflict, vanity",
        "uprightImageSlug": "cukn.jpg",
        "reversedImageSlug": "cukn_reversed.jpg",
        "id": "cukn",
        "color": 49151,
        "uprightMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/knight-of-cups-meaning-tarot-card-meanings#up",
        "reversedMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/knight-of-cups-meaning-tarot-card-meanings#rev"
    },
    {
        "name": "Queen of Cups",
        "element": "Air/Water",
        "sign": "Gemini/Cancer",
        "quality": "",
        "planet": "",
        "uprightKeywords": "Compassion, warmth, kindness, intuition, healer, counsellor, supportive",
        "reversedKeywords": "Insecurity, giving too much, overly-sensitive, needy, fragile, dependence, martyrdom",
        "uprightImageSlug": "cuqu.jpg",
        "reversedImageSlug": "cuqu_reversed.jpg",
        "id": "cuqu",
        "color": 49151,
        "uprightMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/queen-of-cups-meaning-tarot-card-meanings#up",
        "reversedMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/queen-of-cups-meaning-tarot-card-meanings#rev"
    },
    {
        "name": "King of Cups",
        "element": "Air/Water",
        "sign": "Libra/Scorpio",
        "quality": "",
        "planet": "",
        "uprightKeywords": "Wise, diplomatic, balance between head and heart, devoted, advisor, counsellor",
        "reversedKeywords": "Overwhelmed, anxious, cold, repressed, withdrawn, manipulative, selfish",
        "uprightImageSlug": "cuki.jpg",
        "reversedImageSlug": "cuki_reversed.jpg",
        "id": "cuki",
        "color": 49151,
        "uprightMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/king-of-cups-meaning-tarot-card-meanings#up",
        "reversedMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/king-of-cups-meaning-tarot-card-meanings#rev"
    },
    {
        "name": "Ace of Swords",
        "element": "Air",
        "sign": "Gemini/Libra/Aquarius",
        "quality": "",
        "planet": "",
        "uprightKeywords": "Clarity, breakthrough, new idea, concentration, vision, force, focus, truth",
        "reversedKeywords": "Confusion, miscommunication, hostility, arguments, destruction, brutality",
        "uprightImageSlug": "swac.jpg",
        "reversedImageSlug": "swac_reversed.jpg",
        "id": "swac",
        "color": 12632256,
        "uprightMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/ace-of-swords-meaning-tarot-card-meanings#up",
        "reversedMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/ace-of-swords-meaning-tarot-card-meanings#rev"
    },
    {
        "name": "Two of Swords",
        "element": "Air",
        "sign": "Libra",
        "quality": "Cardinal",
        "planet": "Moon",
        "uprightKeywords": "Stalemate, difficult choices, stuck in the middle, denial, hidden information",
        "reversedKeywords": "Indecision, hesitancy, anxiety, too much information, no right choice, truth revealed",
        "uprightImageSlug": "sw02.jpg",
        "reversedImageSlug": "sw02_reversed.jpg",
        "id": "sw02",
        "color": 12632256,
        "uprightMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/two-of-swords-meaning-tarot-card-meanings#up",
        "reversedMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/two-of-swords-meaning-tarot-card-meanings#rev"
    },
    {
        "name": "Three of Swords",
        "element": "Air",
        "sign": "Libra",
        "quality": "Cardinal",
        "planet": "Saturn",
        "uprightKeywords": "Heartbreak, separation, sadness, grief, sorrow, upset, loss, trauma, tears",
        "reversedKeywords": "Healing, forgiveness, recovery, reconciliation, repressing emotions",
        "uprightImageSlug": "sw03.jpg",
        "reversedImageSlug": "sw03_reversed.jpg",
        "id": "sw03",
        "color": 12632256,
        "uprightMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/three-of-swords-meaning-tarot-card-meanings#up",
        "reversedMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/three-of-swords-meaning-tarot-card-meanings#rev"
    },
    {
        "name": "Four of Swords",
        "element": "Air",
        "sign": "Libra",
        "quality": "Cardinal",
        "planet": "Jupiter",
        "uprightKeywords": "Rest, relaxation, peace, sanctuary, recuperation, self-protection, rejuvenation",
        "reversedKeywords": "Recovery, awakening, re-entering world, release from isolation, restlessness, burnout",
        "uprightImageSlug": "sw04.jpg",
        "reversedImageSlug": "sw04_reversed.jpg",
        "id": "sw04",
        "color": 12632256,
        "uprightMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/four-of-swords-meaning-tarot-card-meanings#up",
        "reversedMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/four-of-swords-meaning-tarot-card-meanings#rev"
    },
    {
        "name": "Five of Swords",
        "element": "Air",
        "sign": "Aquarius",
        "quality": "Fixed",
        "planet": "Venus",
        "uprightKeywords": "arguments, disputes, aggression, bullying, intimidation, conflict, hostility, stress",
        "reversedKeywords": "reconciliation, resolution, compromise, revenge, regret, remorse, cutting losses",
        "uprightImageSlug": "sw05.jpg",
        "reversedImageSlug": "sw05_reversed.jpg",
        "id": "sw05",
        "color": 12632256,
        "uprightMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/five-of-swords-meaning-tarot-card-meanings#up",
        "reversedMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/five-of-swords-meaning-tarot-card-meanings#rev"
    },
    {
        "name": "Six of Swords",
        "element": "Air",
        "sign": "Aquarius",
        "quality": "Fixed",
        "planet": "Mercury",
        "uprightKeywords": "Moving on, departure, leaving behind, distance, accepting lessons",
        "reversedKeywords": "Stuck in past, returning to trouble, running away from problems, trapped",
        "uprightImageSlug": "sw06.jpg",
        "reversedImageSlug": "sw06_reversed.jpg",
        "id": "sw06",
        "color": 12632256,
        "uprightMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/six-of-swords-meaning-tarot-card-meanings#up",
        "reversedMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/six-of-swords-meaning-tarot-card-meanings#rev"
    },
    {
        "name": "Seven of Swords",
        "element": "Air",
        "sign": "Aquarius",
        "quality": "Fixed",
        "planet": "Moon",
        "uprightKeywords": "Lies, trickery, scheming, strategy, resourcefulness,sneakiness, cunning",
        "reversedKeywords": "Confession, conscience, regret, maliciousness, truth revealed",
        "uprightImageSlug": "sw07.jpg",
        "reversedImageSlug": "sw07_reversed.jpg",
        "id": "sw07",
        "color": 12632256,
        "uprightMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/seven-of-swords-meaning-tarot-card-meanings#up",
        "reversedMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/seven-of-swords-meaning-tarot-card-meanings#rev"
    },
    {
        "name": "Eight of Swords",
        "element": "Air",
        "sign": "Gemini",
        "quality": "Mutable",
        "planet": "Jupiter",
        "uprightKeywords": "Trapped, restricted, victimised, paralysed, helpless, powerless, imprisonment",
        "reversedKeywords": "Freedom, release, taking control, survivor, facing fears, empowered, surrender",
        "uprightImageSlug": "sw08.jpg",
        "reversedImageSlug": "sw08_reversed.jpg",
        "id": "sw08",
        "color": 12632256,
        "uprightMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/eight-of-swords-meaning-tarot-card-meanings#up",
        "reversedMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/eight-of-swords-meaning-tarot-card-meanings#rev"
    },
    {
        "name": "Nine of Swords",
        "element": "Air",
        "sign": "Gemini",
        "quality": "Mutable",
        "planet": "Mars",
        "uprightKeywords": "fear, anxiety, negativity, breaking point, despair, nightmares, isolation",
        "reversedKeywords": "recovery, learning to cope, facing life, finding help, shame, guilt, mental health issues",
        "uprightImageSlug": "sw09.jpg",
        "reversedImageSlug": "sw09_reversed.jpg",
        "id": "sw09",
        "color": 12632256,
        "uprightMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/nine-of-swords-meaning-tarot-card-meanings#up",
        "reversedMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/nine-of-swords-meaning-tarot-card-meanings#rev"
    },
    {
        "name": "Ten of Swords",
        "element": "Air",
        "sign": "Gemini",
        "quality": "Mutable",
        "planet": "Mercury",
        "uprightKeywords": "ruin, failure, bitterness, collapse, exhaustion, dead end, victimization, betrayal",
        "reversedKeywords": "survival, improvement, healing, lessons learned, despair, relapse",
        "uprightImageSlug": "sw10.jpg",
        "reversedImageSlug": "sw10_reversed.jpg",
        "id": "sw10",
        "color": 12632256,
        "uprightMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/ten-of-swords-meaning-tarot-card-meanings#up",
        "reversedMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/ten-of-swords-meaning-tarot-card-meanings#rev"
    },
    {
        "name": "Page of Swords",
        "element": "Air",
        "sign": "",
        "quality": "",
        "planet": "",
        "uprightKeywords": "Curious, witty, chatty, communicative, inspired, vigilant, alert, mental agility",
        "reversedKeywords": "Scatterbrained, cynical, sarcastic, gossipy, insulting, rude, lack of planning",
        "uprightImageSlug": "swpa.jpg",
        "reversedImageSlug": "swpa_reversed.jpg",
        "id": "swpa",
        "color": 12632256,
        "uprightMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/page-of-swords-meaning-tarot-card-meanings#up",
        "reversedMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/page-of-swords-meaning-tarot-card-meanings#rev"
    },
    {
        "name": "Knight of Swords",
        "element": "Earth/Air",
        "sign": "Taurus/Gemini",
        "quality": "",
        "planet": "",
        "uprightKeywords": "Assertive, direct, impatient, intellectual, daring, focused, perfectionist, ambitious",
        "reversedKeywords": "Rude, tactless, forceful, bully, aggressive, vicious, ruthless, arrogant",
        "uprightImageSlug": "swkn.jpg",
        "reversedImageSlug": "swkn_reversed.jpg",
        "id": "swkn",
        "color": 12632256,
        "uprightMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/knight-of-swords-meaning-tarot-card-meanings#up",
        "reversedMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/knight-of-swords-meaning-tarot-card-meanings#rev"
    },
    {
        "name": "Queen of Swords",
        "element": "Earth/Air",
        "sign": "Virgo/Libra",
        "quality": "",
        "planet": "",
        "uprightKeywords": "Honest, independent, principled, fair, constructive criticism, objective, perceptive",
        "reversedKeywords": "Pessimistic, malicious, manipulative, harsh, bitter, spiteful, cruel, deceitful, unforgiving",
        "uprightImageSlug": "swqu.jpg",
        "reversedImageSlug": "swqu_reversed.jpg",
        "id": "swqu",
        "color": 12632256,
        "uprightMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/queen-of-swords-meaning-tarot-card-meanings#up",
        "reversedMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/queen-of-swords-meaning-tarot-card-meanings#rev"
    },
    {
        "name": "King of Swords",
        "element": "Earth/Air",
        "sign": "Capricorn/Aquarius",
        "quality": "",
        "planet": "",
        "uprightKeywords": "Reason, authority, discipline, integrity, morality, serious, high standards, strict",
        "reversedKeywords": "Irrational, dictator, oppressive, inhumane, controlling, cold, ruthless, dishonest",
        "uprightImageSlug": "swki.jpg",
        "reversedImageSlug": "swki_reversed.jpg",
        "id": "swki",
        "color": 12632256,
        "uprightMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/king-of-swords-meaning-tarot-card-meanings#up",
        "reversedMeaningLink": "https://labyrinthos.co/blogs/tarot-card-meanings-list/king-of-swords-meaning-tarot-card-meanings#rev"
    }
];

