import { ICard } from "./types.js";

export const deck: ICard[] = [
    {
        "name": "0 - The Fool (0: The Fool)",
        "element": "Air",
        "sign": "",
        "quality": "",
        "planet": "Uranus",
        "meaning": "Change and new beginnings",
        "imageSrc": "https://www.sacred-texts.com/tarot/pkt/img/ar00.jpg",
        "id": "ar00",
        "color": 16777215
    },
    {
        "name": "I – The Magician (I: The Magus)",
        "element": "Air",
        "sign": "",
        "quality": "",
        "planet": "Mercury",
        "meaning": "Communication and travel",
        "imageSrc": "https://www.sacred-texts.com/tarot/pkt/img/ar01.jpg",
        "id": "ar01",
        "color": 16777215
    },
    {
        "name": "II – The High Priestess (II: The Priestess)",
        "element": "Water",
        "sign": "",
        "quality": "",
        "planet": "Moon",
        "meaning": "Intuition and memory",
        "imageSrc": "https://www.sacred-texts.com/tarot/pkt/img/ar02.jpg",
        "id": "ar02",
        "color": 16777215
    },
    {
        "name": "III – The Empress (III: The Empress)",
        "element": "Earth",
        "sign": "",
        "quality": "",
        "planet": "Venus",
        "meaning": "Love, comfort, art, and security",
        "imageSrc": "https://www.sacred-texts.com/tarot/pkt/img/ar03.jpg",
        "id": "ar03",
        "color": 16777215
    },
    {
        "name": "IV – The Emperor (IV: The Emperor)",
        "element": "Fire",
        "sign": "Aries",
        "quality": "",
        "planet": "",
        "meaning": "The leader",
        "imageSrc": "https://www.sacred-texts.com/tarot/pkt/img/ar04.jpg",
        "id": "ar04",
        "color": 16777215
    },
    {
        "name": "V – The Hierophant (V: The Hierophant)",
        "element": "Earth",
        "sign": "Taurus",
        "quality": "",
        "planet": "",
        "meaning": "Order and rule",
        "imageSrc": "https://www.sacred-texts.com/tarot/pkt/img/ar05.jpg",
        "id": "ar05",
        "color": 16777215
    },
    {
        "name": "VI – The Lovers (VI: The Lovers)",
        "element": "Air",
        "sign": "Gemini",
        "quality": "",
        "planet": "",
        "meaning": "Choice and duality",
        "imageSrc": "https://www.sacred-texts.com/tarot/pkt/img/ar06.jpg",
        "id": "ar06",
        "color": 16777215
    },
    {
        "name": "VII - The Chariot (VII: The Chariot)",
        "element": "Water",
        "sign": "Cancer",
        "quality": "",
        "planet": "",
        "meaning": "Success, protection, and emotions",
        "imageSrc": "https://www.sacred-texts.com/tarot/pkt/img/ar07.jpg",
        "id": "ar07",
        "color": 16777215
    },
    {
        "name": "VIII – Strength (XI: Lust)",
        "element": "Fire",
        "sign": "Leo",
        "quality": "",
        "planet": "",
        "meaning": "Resilience, control, and glory",
        "imageSrc": "https://www.sacred-texts.com/tarot/pkt/img/ar08.jpg",
        "id": "ar08",
        "color": 16777215
    },
    {
        "name": "IX – The Hermit (IX: The Hermit)",
        "element": "Earth",
        "sign": "Virgo",
        "quality": "",
        "planet": "",
        "meaning": "Analytical thought",
        "imageSrc": "https://www.sacred-texts.com/tarot/pkt/img/ar09.jpg",
        "id": "ar09",
        "color": 16777215
    },
    {
        "name": "X – Wheel of Fortune (X: Fortune)",
        "element": "Fire",
        "sign": "",
        "quality": "",
        "planet": "Jupiter",
        "meaning": "Growth and wisdom",
        "imageSrc": "https://www.sacred-texts.com/tarot/pkt/img/ar10.jpg",
        "id": "ar10",
        "color": 16777215
    },
    {
        "name": "XI – Justice (VIII: Adjustment)",
        "element": "Air",
        "sign": "Libra",
        "quality": "",
        "planet": "",
        "meaning": "Balance",
        "imageSrc": "https://www.sacred-texts.com/tarot/pkt/img/ar11.jpg",
        "id": "ar11",
        "color": 16777215
    },
    {
        "name": "XII – The Hanged Man (XII: The Hanged Man)",
        "element": "Water",
        "sign": "",
        "quality": "",
        "planet": "Neptune",
        "meaning": "Inability to move forward due to illusion, uncertainty, and delusion",
        "imageSrc": "https://www.sacred-texts.com/tarot/pkt/img/ar12.jpg",
        "id": "ar12",
        "color": 16777215
    },
    {
        "name": "XIII – Death (XIII: Death)",
        "element": "Water",
        "sign": "Scorpio",
        "quality": "",
        "planet": "",
        "meaning": "Transformation",
        "imageSrc": "https://www.sacred-texts.com/tarot/pkt/img/ar13.jpg",
        "id": "ar13",
        "color": 16777215
    },
    {
        "name": "XIV – Temperance (XIV: Art)",
        "element": "Fire",
        "sign": "Sagittarius",
        "quality": "",
        "planet": "",
        "meaning": "Understanding through reason and moderation",
        "imageSrc": "https://www.sacred-texts.com/tarot/pkt/img/ar14.jpg",
        "id": "ar14",
        "color": 16777215
    },
    {
        "name": "XV – The Devil (XV: The Devil)",
        "element": "Earth",
        "sign": "Capricorn",
        "quality": "",
        "planet": "",
        "meaning": "Letting go of fear and moving towards liberation",
        "imageSrc": "https://www.sacred-texts.com/tarot/pkt/img/ar15.jpg",
        "id": "ar15",
        "color": 16777215
    },
    {
        "name": "XVI – The Tower (XVI: The Tower)",
        "element": "Fire",
        "sign": "",
        "quality": "",
        "planet": "Mars",
        "meaning": "Unexpected change and action, or arguments",
        "imageSrc": "https://www.sacred-texts.com/tarot/pkt/img/ar16.jpg",
        "id": "ar16",
        "color": 16777215
    },
    {
        "name": "XVII – The Star (XVII: The Star)",
        "element": "Air",
        "sign": "Aquarius",
        "quality": "",
        "planet": "",
        "meaning": "Inspiration and humanitarianism",
        "imageSrc": "https://www.sacred-texts.com/tarot/pkt/img/ar17.jpg",
        "id": "ar17",
        "color": 16777215
    },
    {
        "name": "XVIII – The Moon (XVIII: The Moon)",
        "element": "Water",
        "sign": "Pisces",
        "quality": "",
        "planet": "",
        "meaning": "Imagination and intuition",
        "imageSrc": "https://www.sacred-texts.com/tarot/pkt/img/ar18.jpg",
        "id": "ar18",
        "color": 16777215
    },
    {
        "name": "XIX – The Sun (XIX: The Sun)",
        "element": "Fire",
        "sign": "",
        "quality": "",
        "planet": "Sun",
        "meaning": "Ego and Will",
        "imageSrc": "https://www.sacred-texts.com/tarot/pkt/img/ar19.jpg",
        "id": "ar19",
        "color": 16777215
    },
    {
        "name": "XX – Judgement (XX: The Æon)",
        "element": "Fire/Water",
        "sign": "",
        "quality": "",
        "planet": "Pluto",
        "meaning": "Change, growth, all efforts to rebuild and release",
        "imageSrc": "https://www.sacred-texts.com/tarot/pkt/img/ar20.jpg",
        "id": "ar20",
        "color": 16777215
    },
    {
        "name": "XXI – The World (XXI: The Universe)",
        "element": "Earth",
        "sign": "",
        "quality": "",
        "planet": "Saturn",
        "meaning": "Rewards through completion",
        "imageSrc": "https://www.sacred-texts.com/tarot/pkt/img/ar21.jpg",
        "id": "ar21",
        "color": 16777215
    },
    {
        "name": "Ace of Wands (The Root of the Powers of Fire)",
        "element": "Fire",
        "sign": "Aries/Leo/Sagittarius",
        "quality": "",
        "planet": "",
        "meaning": "Inspiration, new opportunities, growth, potential",
        "imageSrc": "https://www.sacred-texts.com/tarot/pkt/img/waac.jpg",
        "id": "waac",
        "color": 14596231
    },
    {
        "name": "Two of Wands (Dominion)",
        "element": "Fire",
        "sign": "Aries",
        "quality": "Cardinal",
        "planet": "Mars",
        "meaning": "Planning, progress, decision, discovery",
        "imageSrc": "https://www.sacred-texts.com/tarot/pkt/img/wa02.jpg",
        "id": "wa02",
        "color": 14596231
    },
    {
        "name": "Three of Wands (Virtue)",
        "element": "Fire",
        "sign": "Aries",
        "quality": "Cardinal",
        "planet": "Sun",
        "meaning": "Expansion, foresight, opportunity",
        "imageSrc": "https://www.sacred-texts.com/tarot/pkt/img/wa03.jpg",
        "id": "wa03",
        "color": 14596231
    },
    {
        "name": "Four of Wands (Completion)",
        "element": "Fire",
        "sign": "Aries",
        "quality": "Cardinal",
        "planet": "Venus",
        "meaning": "Celebration, joy, relaxation",
        "imageSrc": "https://www.sacred-texts.com/tarot/pkt/img/wa04.jpg",
        "id": "wa04",
        "color": 14596231
    },
    {
        "name": "Five of Wands (Strife)",
        "element": "Fire",
        "sign": "Leo",
        "quality": "Fixed",
        "planet": "Saturn",
        "meaning": "Competition, tension, conflict",
        "imageSrc": "https://www.sacred-texts.com/tarot/pkt/img/wa05.jpg",
        "id": "wa05",
        "color": 14596231
    },
    {
        "name": "Six of Wands (Victory)",
        "element": "Fire",
        "sign": "Leo",
        "quality": "Fixed",
        "planet": "Jupiter",
        "meaning": "Public recognition, self-confidence",
        "imageSrc": "https://www.sacred-texts.com/tarot/pkt/img/wa06.jpg",
        "id": "wa06",
        "color": 14596231
    },
    {
        "name": "Seven of Wands (Valour)",
        "element": "Fire",
        "sign": "Leo",
        "quality": "Fixed",
        "planet": "Mars",
        "meaning": "Challenge, competition, perseverance",
        "imageSrc": "https://www.sacred-texts.com/tarot/pkt/img/wa07.jpg",
        "id": "wa07",
        "color": 14596231
    },
    {
        "name": "Eight of Wands (Swiftness)",
        "element": "Fire",
        "sign": "Sagittarius",
        "quality": "Mutable",
        "planet": "Mercury",
        "meaning": "Action, movement, swift change",
        "imageSrc": "https://www.sacred-texts.com/tarot/pkt/img/wa08.jpg",
        "id": "wa08",
        "color": 14596231
    },
    {
        "name": "Nine of Wands (Strength)",
        "element": "Fire",
        "sign": "Sagittarius",
        "quality": "Mutable",
        "planet": "Moon",
        "meaning": "Courage, persistence, resilience",
        "imageSrc": "https://www.sacred-texts.com/tarot/pkt/img/wa09.jpg",
        "id": "wa09",
        "color": 14596231
    },
    {
        "name": "Ten of Wands (Oppression)",
        "element": "Fire",
        "sign": "Sagittarius",
        "quality": "Mutable",
        "planet": "Saturn",
        "meaning": "Burden, responsibility, work, completion",
        "imageSrc": "https://www.sacred-texts.com/tarot/pkt/img/wa10.jpg",
        "id": "wa10",
        "color": 14596231
    },
    {
        "name": "Page of Wands (Princess of Wands)",
        "element": "Fire",
        "sign": "",
        "quality": "",
        "planet": "",
        "meaning": "Enthusiasm, exploration, discovery, free spirit",
        "imageSrc": "https://www.sacred-texts.com/tarot/pkt/img/wapa.jpg",
        "id": "wapa",
        "color": 14596231
    },
    {
        "name": "Knight of Wands (Prince of Wands)",
        "element": "Water/Fire",
        "sign": "Scorpio/Sagittarius",
        "quality": "",
        "planet": "",
        "meaning": "Energy, passion, action, adventure, impulsiveness",
        "imageSrc": "https://www.sacred-texts.com/tarot/pkt/img/wakn.jpg",
        "id": "wakn",
        "color": 14596231
    },
    {
        "name": "Queen of Wands (Queen of Wands)",
        "element": "Water/Fire",
        "sign": "Pisces/Aries",
        "quality": "",
        "planet": "",
        "meaning": "Warmth, passion, determination",
        "imageSrc": "https://www.sacred-texts.com/tarot/pkt/img/waqu.jpg",
        "id": "waqu",
        "color": 14596231
    },
    {
        "name": "King of Wands (Knight of Wands)",
        "element": "Water/Fire",
        "sign": "Cancer/Leo",
        "quality": "",
        "planet": "",
        "meaning": "Natural leader, vision, honour",
        "imageSrc": "https://www.sacred-texts.com/tarot/pkt/img/waki.jpg",
        "id": "waki",
        "color": 14596231
    },
    {
        "name": "Ace of Pentacles (The Root of the Powers of Earth)",
        "element": "Earth",
        "sign": "Taurus/Virgo/Capricorn",
        "quality": "",
        "planet": "",
        "meaning": "Manifestation, opportunity, prosperity",
        "imageSrc": "https://www.sacred-texts.com/tarot/pkt/img/peac.jpg",
        "id": "peac",
        "color": 16776960
    },
    {
        "name": "Two of Pentacles (Change)",
        "element": "Earth",
        "sign": "Capricorn",
        "quality": "Cardinal",
        "planet": "Jupiter",
        "meaning": "Balance, adaptability, prioritization",
        "imageSrc": "https://www.sacred-texts.com/tarot/pkt/img/pe02.jpg",
        "id": "pe02",
        "color": 16776960
    },
    {
        "name": "Three of Pentacles (Works)",
        "element": "Earth",
        "sign": "Capricorn",
        "quality": "Cardinal",
        "planet": "Mars",
        "meaning": "Teamwork, collaboration, learning",
        "imageSrc": "https://www.sacred-texts.com/tarot/pkt/img/pe03.jpg",
        "id": "pe03",
        "color": 16776960
    },
    {
        "name": "Four of Pentacles (Power)",
        "element": "Earth",
        "sign": "Capricorn",
        "quality": "Cardinal",
        "planet": "Sun",
        "meaning": "Saving money, security, control, scarcity",
        "imageSrc": "https://www.sacred-texts.com/tarot/pkt/img/pe04.jpg",
        "id": "pe04",
        "color": 16776960
    },
    {
        "name": "Five of Pentacles (Worry)",
        "element": "Earth",
        "sign": "Taurus",
        "quality": "Fixed",
        "planet": "Mercury",
        "meaning": "Isolation, insecurity, worry, loss, poverty",
        "imageSrc": "https://www.sacred-texts.com/tarot/pkt/img/pe05.jpg",
        "id": "pe05",
        "color": 16776960
    },
    {
        "name": "Six of Pentacles (Success)",
        "element": "Earth",
        "sign": "Taurus",
        "quality": "Fixed",
        "planet": "Moon",
        "meaning": "Gifts, generosity, charity",
        "imageSrc": "https://www.sacred-texts.com/tarot/pkt/img/pe06.jpg",
        "id": "pe06",
        "color": 16776960
    },
    {
        "name": "Seven of Pentacles (Failure)",
        "element": "Earth",
        "sign": "Taurus",
        "quality": "Fixed",
        "planet": "Saturn",
        "meaning": "Vision, perseverance, reward, prosperity",
        "imageSrc": "https://www.sacred-texts.com/tarot/pkt/img/pe07.jpg",
        "id": "pe07",
        "color": 16776960
    },
    {
        "name": "Eight of Pentacles (Prudence)",
        "element": "Earth",
        "sign": "Virgo",
        "quality": "Mutable",
        "planet": "Sun",
        "meaning": "Repetition, mastery, development",
        "imageSrc": "https://www.sacred-texts.com/tarot/pkt/img/pe08.jpg",
        "id": "pe08",
        "color": 16776960
    },
    {
        "name": "Nine of Pentacles (Gain)",
        "element": "Earth",
        "sign": "Virgo",
        "quality": "Mutable",
        "planet": "Venus",
        "meaning": "Gratitude, luxury, self-sufficiency, culmination",
        "imageSrc": "https://www.sacred-texts.com/tarot/pkt/img/pe09.jpg",
        "id": "pe09",
        "color": 16776960
    },
    {
        "name": "Ten of Pentacles (Wealth)",
        "element": "Earth",
        "sign": "Virgo",
        "quality": "Mutable",
        "planet": "Mercury",
        "meaning": "Wealth, family, establishment",
        "imageSrc": "https://www.sacred-texts.com/tarot/pkt/img/pe10.jpg",
        "id": "pe10",
        "color": 16776960
    },
    {
        "name": "Page of Pentacles (Princess of Disks)",
        "element": "Earth",
        "sign": "",
        "quality": "",
        "planet": "",
        "meaning": "Manifestation, opportunity, wealth",
        "imageSrc": "https://www.sacred-texts.com/tarot/pkt/img/pepa.jpg",
        "id": "pepa",
        "color": 16776960
    },
    {
        "name": "Knight of Pentacles (Prince of Disks)",
        "element": "Fire/Earth",
        "sign": "Leo/Virgo",
        "quality": "",
        "planet": "",
        "meaning": "Work, routine, scarcity",
        "imageSrc": "https://www.sacred-texts.com/tarot/pkt/img/pekn.jpg",
        "id": "pekn",
        "color": 16776960
    },
    {
        "name": "Queen of Pentacles (Queen of Disks)",
        "element": "Fire/Earth",
        "sign": "Sagittarius/Capricorn",
        "quality": "",
        "planet": "",
        "meaning": "Practicality, warmth, security",
        "imageSrc": "https://www.sacred-texts.com/tarot/pkt/img/pequ.jpg",
        "id": "pequ",
        "color": 16776960
    },
    {
        "name": "King of Pentacles (Knight of Disks)",
        "element": "Fire/Earth",
        "sign": "Aries/Taurus",
        "quality": "",
        "planet": "",
        "meaning": "Wealth, leadership, security, discipline, abundance",
        "imageSrc": "https://www.sacred-texts.com/tarot/pkt/img/peki.jpg",
        "id": "peki",
        "color": 16776960
    },
    {
        "name": "Ace of Cups (The Root of the Powers of Water)",
        "element": "Water",
        "sign": "Cancer/Scorpio/Pisces",
        "quality": "",
        "planet": "",
        "meaning": "Love, compassion, creativity",
        "imageSrc": "https://www.sacred-texts.com/tarot/pkt/img/cuac.jpg",
        "id": "cuac",
        "color": 49151
    },
    {
        "name": "Two of Cups (Love)",
        "element": "Water",
        "sign": "Cancer",
        "quality": "Cardinal",
        "planet": "Venus",
        "meaning": "True love, partnership, mutual attraction",
        "imageSrc": "https://www.sacred-texts.com/tarot/pkt/img/cu02.jpg",
        "id": "cu02",
        "color": 49151
    },
    {
        "name": "Three of Cups (Abundance)",
        "element": "Water",
        "sign": "Cancer",
        "quality": "Cardinal",
        "planet": "Mercury",
        "meaning": "Celebration, friendship, creativity, collaboration",
        "imageSrc": "https://www.sacred-texts.com/tarot/pkt/img/cu03.jpg",
        "id": "cu03",
        "color": 49151
    },
    {
        "name": "Four of Cups (Luxury)",
        "element": "Water",
        "sign": "Cancer",
        "quality": "Cardinal",
        "planet": "Moon",
        "meaning": "Meditation, apathy, re-evaluation",
        "imageSrc": "https://www.sacred-texts.com/tarot/pkt/img/cu04.jpg",
        "id": "cu04",
        "color": 49151
    },
    {
        "name": "Five of Cups (Disappointment)",
        "element": "Water",
        "sign": "Scorpio",
        "quality": "Fixed",
        "planet": "Mars",
        "meaning": "Regret, failure, disappointment, pessimism",
        "imageSrc": "https://www.sacred-texts.com/tarot/pkt/img/cu05.jpg",
        "id": "cu05",
        "color": 49151
    },
    {
        "name": "Six of Cups (Pleasure)",
        "element": "Water",
        "sign": "Scorpio",
        "quality": "Fixed",
        "planet": "Sun",
        "meaning": "Nostalgia, memory, joy",
        "imageSrc": "https://www.sacred-texts.com/tarot/pkt/img/cu06.jpg",
        "id": "cu06",
        "color": 49151
    },
    {
        "name": "Seven of Cups (Debauch)",
        "element": "Water",
        "sign": "Scorpio",
        "quality": "Fixed",
        "planet": "Venus",
        "meaning": "Opportunity, choice, illusion",
        "imageSrc": "https://www.sacred-texts.com/tarot/pkt/img/cu07.jpg",
        "id": "cu07",
        "color": 49151
    },
    {
        "name": "Eight of Cups (Indolence)",
        "element": "Water",
        "sign": "Pisces",
        "quality": "Mutable",
        "planet": "Saturn",
        "meaning": "Disappointment, abandonment, withdrawal, escapism",
        "imageSrc": "https://www.sacred-texts.com/tarot/pkt/img/cu08.jpg",
        "id": "cu08",
        "color": 49151
    },
    {
        "name": "Nine of Cups (Happiness)",
        "element": "Water",
        "sign": "Pisces",
        "quality": "Mutable",
        "planet": "Jupiter",
        "meaning": "Contentment, satisfaction, gratitude, wish come true",
        "imageSrc": "https://www.sacred-texts.com/tarot/pkt/img/cu09.jpg",
        "id": "cu09",
        "color": 49151
    },
    {
        "name": "Ten of Cups (Satiety)",
        "element": "Water",
        "sign": "Pisces",
        "quality": "Mutable",
        "planet": "Mars",
        "meaning": "Harmony, love, happiness, alignment, satisfaction",
        "imageSrc": "https://www.sacred-texts.com/tarot/pkt/img/cu10.jpg",
        "id": "cu10",
        "color": 49151
    },
    {
        "name": "Page of Cups (Princess of Cups)",
        "element": "Water",
        "sign": "",
        "quality": "",
        "planet": "",
        "meaning": "Creativity, opportunity, intuition, curiosity, possibility",
        "imageSrc": "https://www.sacred-texts.com/tarot/pkt/img/cupa.jpg",
        "id": "cupa",
        "color": 49151
    },
    {
        "name": "Knight of Cups (Prince of Cups)",
        "element": "Air/Water",
        "sign": "Aquarius/Pisces",
        "quality": "",
        "planet": "",
        "meaning": "Creativity, romance, charm, imagination, beauty",
        "imageSrc": "https://www.sacred-texts.com/tarot/pkt/img/cukn.jpg",
        "id": "cukn",
        "color": 49151
    },
    {
        "name": "Queen of Cups (Queen of Cups)",
        "element": "Air/Water",
        "sign": "Gemini/Cancer",
        "quality": "",
        "planet": "",
        "meaning": "Emotional security, intuition, compassion",
        "imageSrc": "https://www.sacred-texts.com/tarot/pkt/img/cuqu.jpg",
        "id": "cuqu",
        "color": 49151
    },
    {
        "name": "King of Cups (Knight of Cups)",
        "element": "Air/Water",
        "sign": "Libra/Scorpio",
        "quality": "",
        "planet": "",
        "meaning": "Emotional balance, compassion, diplomacy",
        "imageSrc": "https://www.sacred-texts.com/tarot/pkt/img/cuki.jpg",
        "id": "cuki",
        "color": 49151
    },
    {
        "name": "Ace of Swords (The Root of the Powers of Air)",
        "element": "Air",
        "sign": "Gemini/Libra/Aquarius",
        "quality": "",
        "planet": "",
        "meaning": "Breakthrough, new ideas, mental clarity, success",
        "imageSrc": "https://www.sacred-texts.com/tarot/pkt/img/swac.jpg",
        "id": "swac",
        "color": 12632256
    },
    {
        "name": "Two of Swords (Peace)",
        "element": "Air",
        "sign": "Libra",
        "quality": "Cardinal",
        "planet": "Moon",
        "meaning": "Difficult choices, impasse, truce",
        "imageSrc": "https://www.sacred-texts.com/tarot/pkt/img/sw02.jpg",
        "id": "sw02",
        "color": 12632256
    },
    {
        "name": "Three of Swords (Sorrow)",
        "element": "Air",
        "sign": "Libra",
        "quality": "Cardinal",
        "planet": "Saturn",
        "meaning": "Heartbreak , emotional pain, hurt",
        "imageSrc": "https://www.sacred-texts.com/tarot/pkt/img/sw03.jpg",
        "id": "sw03",
        "color": 12632256
    },
    {
        "name": "Four of Swords (Truce)",
        "element": "Air",
        "sign": "Libra",
        "quality": "Cardinal",
        "planet": "Jupiter",
        "meaning": "Rest, relaxation, contemplation, recovery",
        "imageSrc": "https://www.sacred-texts.com/tarot/pkt/img/sw04.jpg",
        "id": "sw04",
        "color": 12632256
    },
    {
        "name": "Five of Swords (Defeat)",
        "element": "Air",
        "sign": "Aquarius",
        "quality": "Fixed",
        "planet": "Venus",
        "meaning": "Conflict, disagreement, competition, defeat, winning at all costs",
        "imageSrc": "https://www.sacred-texts.com/tarot/pkt/img/sw05.jpg",
        "id": "sw05",
        "color": 12632256
    },
    {
        "name": "Six of Swords (Science)",
        "element": "Air",
        "sign": "Aquarius",
        "quality": "Fixed",
        "planet": "Mercury",
        "meaning": "Sad but needed, letting go of baggage",
        "imageSrc": "https://www.sacred-texts.com/tarot/pkt/img/sw06.jpg",
        "id": "sw06",
        "color": 12632256
    },
    {
        "name": "Seven of Swords (Futility)",
        "element": "Air",
        "sign": "Aquarius",
        "quality": "Fixed",
        "planet": "Moon",
        "meaning": "Betrayal, deception, getting away with something",
        "imageSrc": "https://www.sacred-texts.com/tarot/pkt/img/sw07.jpg",
        "id": "sw07",
        "color": 12632256
    },
    {
        "name": "Eight of Swords (Interference)",
        "element": "Air",
        "sign": "Gemini",
        "quality": "Mutable",
        "planet": "Jupiter",
        "meaning": "Isolation, self-imposed restriction",
        "imageSrc": "https://www.sacred-texts.com/tarot/pkt/img/sw08.jpg",
        "id": "sw08",
        "color": 12632256
    },
    {
        "name": "Nine of Swords (Cruelty)",
        "element": "Air",
        "sign": "Gemini",
        "quality": "Mutable",
        "planet": "Mars",
        "meaning": "Indecision, truce, stalemate, blocked emotion",
        "imageSrc": "https://www.sacred-texts.com/tarot/pkt/img/sw09.jpg",
        "id": "sw09",
        "color": 12632256
    },
    {
        "name": "Ten of Swords (Ruin)",
        "element": "Air",
        "sign": "Gemini",
        "quality": "Mutable",
        "planet": "Mercury",
        "meaning": "Painful end, deep wounds, betrayal, loss, crisis",
        "imageSrc": "https://www.sacred-texts.com/tarot/pkt/img/sw10.jpg",
        "id": "sw10",
        "color": 12632256
    },
    {
        "name": "Page of Swords (Princess of Swords)",
        "element": "Air",
        "sign": "",
        "quality": "",
        "planet": "",
        "meaning": "Talkative, curious, mentally restless, energetic",
        "imageSrc": "https://www.sacred-texts.com/tarot/pkt/img/swpa.jpg",
        "id": "swpa",
        "color": 12632256
    },
    {
        "name": "Knight of Swords (Prince of Swords)",
        "element": "Earth/Air",
        "sign": "Taurus/Gemini",
        "quality": "",
        "planet": "",
        "meaning": "Ambition, action, fast-thinking",
        "imageSrc": "https://www.sacred-texts.com/tarot/pkt/img/swkn.jpg",
        "id": "swkn",
        "color": 12632256
    },
    {
        "name": "Queen of Swords (Queen of Swords)",
        "element": "Earth/Air",
        "sign": "Virgo/Libra",
        "quality": "",
        "planet": "",
        "meaning": "Independence, unbiased judgement, clear boundaries, direct communication",
        "imageSrc": "https://www.sacred-texts.com/tarot/pkt/img/swqu.jpg",
        "id": "swqu",
        "color": 12632256
    },
    {
        "name": "King of Swords (Knight of Swords)",
        "element": "Earth/Air",
        "sign": "Capricorn/Aquarius",
        "quality": "",
        "planet": "",
        "meaning": "Mental clarity, intellectual power, authority, truth",
        "imageSrc": "https://www.sacred-texts.com/tarot/pkt/img/swki.jpg",
        "id": "swki",
        "color": 12632256
    }
];

